### ISSUE TITLE
Code blocks don't show in mod descriptions

### ISSUE THREAD

**Issue by u4pak** [RiftFN/Mods#9]
**Bug:**  Multiline code blocks made with markdown do not show properly in a mod's description.

**Expected Result:** Multiline code block displays properly.

**Steps to replicate:**
- Open the Rift launcher and go to the Marketplace
- Go to any mod with a code block in the description (Ex: AllyWeapons)
- Scroll down to where the code block is supposed to be

**Example:** 
![errorcb](https://user-images.githubusercontent.com/71219957/177611684-668407de-754c-4eaf-ac15-92926757684f.png)
<div align="center">
On the left is the expected result, the right is the true outcome
</div>

**Comment by jb0s** [comment]
This bug is due to the nature of how I implemented markdown in the Rift Launcher a while ago. I'll make sure that the markdown is 100% implemented in the next release.

**Comment by mrpow737** [comment]
fixed

**Comment by jb0s** [comment]
> fixed

It's definitely not fixed. The marketplace is currently down due to issues with my name provider.
